### ISSUE TITLE
Grouping components

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#39]
If I write groups for components in the interpretation portal (let's component VRM-ViscousRemanence, and componet MT- Medium temperature and HT- High...) Then I can export but without seeing anything in the stereonet.  Is that correct? I would expect being able to see the different components (either all in the plot with colors or changing them with a shortcut) and the possibility to merge them or not or export them separately and fitting circles between them, for example.

**Comment by Jollyfant** [comment]
The stereonet in the tab shows all the components in the "active" group. You cannot view different groups at the same time. If you want to change the group of a specimen you need to go back to the interpretation. Maybe I can make some more helpful options to merge groups together.

**Comment by dpastorgalan** [comment]
Maybe it is only me, but I have a tendency to analyze in specimen coordinates and then check how those groups are. If after check I have the feeling that two components are not so distinct than they looked in the Zeijdervelds (let's say 3-5 degrees of difference), I try to merge them, before statistics. But if nobody complains, it is fine.

Also, in addition of a shortcut writing the group name, wouldn't it be possible one that jumps from one to other in alphabetic/numeric order? If that is hard, it is also ok.

**Comment by Jollyfant** [comment]
Sort of implemented with https://github.com/Jollyfant/PMAG2/commit/c8eb7983acc24f9f3af06534e93ae46fa793caa9. You can now quickly switch groups on the interpreted components page and see what group is active.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/10128244/67301991-7a23b680-f4f0-11e9-9ec9-e2e1f0b53972.png">

**Comment by Jollyfant** [comment]
Added merging of groups by double click in https://github.com/Jollyfant/PMAG2/commit/173de576bed85ed45335187ef09ca1adde6f72c7.

Should help the workflow!

**Comment by dpastorgalan** [comment]
It does! And it looks perfect (also it shows all components so if you mislabeled one you can easily correct it ☝️) . Love it!

Now I only miss the Statistics portal being capable to import components ("groups") as different collections (but that is other open issue)

**Comment by Jollyfant** [comment]
So you would expect all groups to be in the exported interpretation file and then when it's loaded to the statistic portal it sorts by group and adds three collections?

Collection - ChRM
Collection - Group1
Collection - Group2

**Comment by Jollyfant** [comment]
Testing this in 1f7de927802c2534ffe79f44c885fc9d223d9083. Can you try on beta.paleomagnetism.org to see if its how you expect? I like this idea!

**Comment by dpastorgalan** [comment]
This is EXACTLY what I wanted! I Love it!!
Then you can try if some of the components you separated are statistically the same (in the CTMD) and if so you can combine, or combine overprinted directions from several sites creating an "overprint locality"

Maybe I am the only one that loves that, but before I had to save several files when I had two components (which in my samples is kind of common).

**Comment by Jollyfant** [comment]
Okay great :) thanks for the suggestions
