### ISSUE TITLE
Grouping and exporting groups

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#40]
Grouping is great and really helpful. However, when opening the .dir file in the statistics portal, both groups form part of the same collection, and there is not (at least an obvious)form to separate them. For example, I have this file (attached) with a clear present day overprint and one component that is to the South East. I have separated them in groups (3 groups, but one might be incorrect).

I think the possibility to separate those groups into different collections directly (and not saving two different files by deleting interpretations etc) will facilitate the workflow. In fact, if we can choose which groups to separate or not in the statistics portal into collections I do not think my previous concern about grouping is relevant. I think it is a good solution, that improves the workflow, and transparency, You share your .dir file with the groups you think you have, and then the statistics with the collections, that may merge some groups based on statistics.
z
[?.dir.zip](https://github.com/Jollyfant/PMAG2/files/3692731/dir.zip)

**Comment by Jollyfant** [comment]
Added in 1f7de927802c2534ffe79f44c885fc9d223d9083.
