### ISSUE TITLE
Collection of details

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#42]
1: In the beta version, statistic portal do not open (or not always) .dir (2.0) files. This does not happen in the Master version. Example: 
[H.dir.zip](https://github.com/Jollyfant/PMAG2/files/3695383/H.dir.zip)

2: When saving a .dir file in where I have fitted circles the interpretation opens the saved points in the statistics. However, if I open the .dir again in the interpretation, I can only see the fitted direction and not the interpreted circle (and I do not know how to recover the circle). I think the fit chosen (line or plane) is the one that has to be preserved in the .dir file by default -what the user interpret from the raw data. I like the idea of keeping the fitted points as well, but that has to be in addition, and not the only.

3. This is a suggestion. I still think that the final great circle fit should be in the statistics section, where you can decide collections (in the end a great circle could be used for two components, with two fits, for example one original and an overprint). Also some times, It is a good idea combining several sites into localities with far more set points and then fit the circles more accurately. We can't do that now.

**Comment by Jollyfant** [comment]
1 & 2 should be fixed. I think it fits better with interpretation because there is a lot of massaging going on and not statistics.

**Comment by dpastorgalan** [comment]
It works for me...

**Comment by Jollyfant** [comment]
Good! Closing.. thanks for the input :)
