### ISSUE TITLE
Importing data in the import window: empty stereonets

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#46]
Hi Jollyfant,

I've been testing the importing windows both through .csv files and in the importing window and, although the software says it does it, the results do not show in the stereonets that appear empty (or do not show at all).

This is a thing that we would like to fix, if we want old farts to use the platform and share their older results combined with newer etc, we need that option. Because for most of them re-fitting the data in the interpretation portal won't be an option (although it would be the best one)

**Comment by Jollyfant** [comment]
Can you give example input?

**Comment by dpastorgalan** [comment]
Sorry, I forgot this.
I have tried this in all versions (with no strike and dip, with no naming per core, adding and not coordinates and times. I have also tried without negative signs and with and without decimals. I have tried also adding random beddings.
```
-24, 20, 0, 0, a
16, -13, 0, 0, b
-5, -4, 0, 0, c
26, 20, 0, 0, d
0, 17, 0, 0, e
24, 3, 0, 0, f
10, 5, 0, 0, g
-3, 5, 0, 0, h
```

**Comment by Jollyfant** [comment]
Fixed in 058cdb5d72e90c2567e8cc9581bb89b46a4d683b. It was not accepting negative declinations because .. that's weird! Now it just wraps to dec + 360.

**Comment by dpastorgalan** [comment]
I do not think that was the mistake. I had tried positive and negative declinations, inclinations and beddings. It keeps not showing the stereonets nor calculating the the statistics.

**Comment by Jollyfant** [comment]
Does it give an error when it doesn't show the stereonets?

**Comment by dpastorgalan** [comment]
Not at all. Maybe it is just a misconnection between the input and the matrices the code analyses?

**Comment by Jollyfant** [comment]
If I take the example and paste it in the input window there is not a problem for me. Can you open the developer console (F12) and look at the console error message there please?

![image](https://user-images.githubusercontent.com/10128244/73637871-8845af00-4669-11ea-82f3-dd1f1d935542.png)

**Comment by dpastorgalan** [comment]
Ok, it works now. I think that either I was using the master version or a local or cached version of the developing version.
