### ISSUE TITLE
Export .kml does not work

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#47]
I have exported the kml file (attached) and it does not open in Google Earth.

> Open of file "/Users/danielpastorgalan/Downloads/collections.kml" failed: Only a single root feature allowed within <kml> tag

I have checked for the error in internet. However, the answers I found are not coincident with the paleomagnetism produced files. After checking the file, I couldn't see any problem so I think the problem is the graphic repository where it points to get the symbols. I am not 100% sure.
[collections.kml.zip](https://github.com/Jollyfant/PMAG2/files/4132105/collections.kml.zip)

**Comment by Jollyfant** [comment]
Fixed in 9f2417233ac30db9e626b1449397b3ff99d76767. Google Earth cannot show the markers as confidence parachutes but just shows point locations.
