### ISSUE TITLE
Problems submission data to the library

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#69]
I am trying to submit .pub files to the library. The files were originally .pmag, I re-exported them as .pub (I am planning also to do .col files with the .dir ones but wanted first this).

Files are the following:
[Rezaeian_2020.zip](https://github.com/Jollyfant/PMAG2/files/4537011/Rezaeian_2020.zip)

And for all of our readers (!!) this is the associated paper:
https://www.sciencedirect.com/science/article/pii/S0040195120301426#ec0005

And this is the associated DOI: 
https://doi.org/10.1016/j.tecto.2020.228459

So if someone is reading this and want this files get them and cite us!

**Comment by Jollyfant** [comment]
`.pub` files cannot be submitted to the library unfortunately. We only accept collection files (`.col`) because of the clearer data provenance (who made it and where does it come from). This is much better with the demagnetisation data instead of random dec, inc pairs.

**Comment by dpastorgalan** [comment]
Makes sense. This is going to be a little painful then, because the original files are pmag 1.0 so I think I'll have to work a to update all the details.

**Comment by Jollyfant** [comment]
Yep, sorry. You can load pmag 1.0 files to the interpretation portal and add the extra metadata there (per specimen; or apply to all). But make sure they load OK!
